DO $$
BEGIN
  CREATE TYPE "CanonicalRoleKey" AS ENUM (
    'PLATFORM_SUPER_ADMIN',
    'PLATFORM_BILLING_ADMIN',
    'PLATFORM_NOC_LEAD',
    'TENANT_ADMIN',
    'STATION_MANAGER',
    'SITE_HOST',
    'ROAMING_MANAGER',
    'FLEET_DISPATCHER',
    'FLEET_DRIVER',
    'INSTALLER_AGENT',
    'SMART_CHARGING_ENGINEER',
    'OPERATIONS_OPERATOR',
    'FIELD_TECHNICIAN',
    'TENANT_FINANCE_ANALYST',
    'EXTERNAL_PROVIDER_OPERATOR'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'PLATFORM_SUPER_ADMIN';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'PLATFORM_BILLING_ADMIN';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'PLATFORM_NOC_LEAD';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'TENANT_ADMIN';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'STATION_MANAGER';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'SITE_HOST';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'ROAMING_MANAGER';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'FLEET_DISPATCHER';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'FLEET_DRIVER';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'INSTALLER_AGENT';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'SMART_CHARGING_ENGINEER';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'OPERATIONS_OPERATOR';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'FIELD_TECHNICIAN';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'TENANT_FINANCE_ANALYST';
ALTER TYPE "CanonicalRoleKey" ADD VALUE IF NOT EXISTS 'EXTERNAL_PROVIDER_OPERATOR';

ALTER TABLE "organization_memberships"
  ADD COLUMN IF NOT EXISTS "canonicalRoleKey" "CanonicalRoleKey";

ALTER TABLE "user_invitations"
  ADD COLUMN IF NOT EXISTS "canonicalRoleKey" "CanonicalRoleKey";
